<?php

namespace AppBundle\Repository;

/**
 * answerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCorrectsAnswers($question){
        $qb = $this->createQueryBuilder('ans');
        $qb -> select('ans')
            ->andWhere('ans.question = :question')
            ->setParameter('question', $question)
            ->andWhere('ans.correct = :correct')
            ->setParameter('correct', 1);

        return $qb->getQuery()->getResult();
    }

}
