<?php

namespace AppBundle\Repository;

/**
 * answerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikeQueryBuilder($pattern)
    {
        return $this->createQueryBuilder('ans')
            ->where('ans.value LIKE :pattern')
            ->setParameter('pattern',$pattern);

    }
}
