<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllKeys() {
        $result = $this->createQueryBuilder('s')->select('s.sKey')->getQuery()->getArrayResult();

        return $result;
    }
}
