# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers


    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: bcrypt

    role-hierarchy:
        ROLE_ADMIN: [ROLE_TEACHER]

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

        #in_memory:
        #    memory:
        #        users:
        #            etudiant: {password: etudiant, roles: ['ROLE_STUDENT'] }
        #            enseignant: {password: enseignant, roles: ['ROLE_TEACHER'] }
        #            admin:   {password: admin, roles: ['ROLE_ADMIN'] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            # form_login: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # app/config/security.yml

           # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate


            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html


    access_control:
        - { path: ^/addquestion, roles: ROLE_TEACHER }