<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0xfycxx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0xfycxx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0xfycxx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0xfycxx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0xfycxx\appProdProjectContainer(array(
    'container.build_hash' => '0xfycxx',
    'container.build_id' => 'e553ae28',
    'container.build_time' => 1519397311,
));
