<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsphuhf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsphuhf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMsphuhf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMsphuhf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMsphuhf\appProdProjectContainer(array(
    'container.build_hash' => 'Msphuhf',
    'container.build_id' => '525a89ac',
    'container.build_time' => 1523535408,
));
