<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfi0dkm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfi0dkm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJfi0dkm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJfi0dkm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJfi0dkm\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jfi0dkm',
    'container.build_id' => '85d44b38',
    'container.build_time' => 1523259848,
));
