<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYkwhxxy\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYkwhxxy/appDevProjectContainer.php') {
    touch(__DIR__.'/ContainerYkwhxxy.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\ContainerYkwhxxy\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \ContainerYkwhxxy\appDevProjectContainer(array(
    'container.build_hash' => 'Ykwhxxy',
    'container.build_id' => 'ae319fca',
    'container.build_time' => 1519396463,
));
