<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsn6hnt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsn6hnt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOsn6hnt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOsn6hnt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerOsn6hnt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Osn6hnt',
    'container.build_id' => 'd1ddd816',
    'container.build_time' => 1523604712,
));
