<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrkltjt\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrkltjt/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUrkltjt.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUrkltjt\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUrkltjt\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Urkltjt',
    'container.build_id' => '2fcd4db3',
    'container.build_time' => 1523439186,
));
