<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RequestMatcher.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Http/AccessMap.php';

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/addquestion'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/listquiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/editquiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/displayquestions'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/createquiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/createsession'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/deletequestion'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/deletequestionfromquiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/loadquiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/deletequiz'), array(0 => 'ROLE_TEACHER'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/listUser'), array(0 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/editUser'), array(0 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/administration'), array(0 => 'ROLE_ADMIN'), NULL);

return $instance;
